# The URL the site will be built for
base_url = "https://kosticmarko.blog"

# Whether to build a search index to be used later on by a JavaScript library
theme = "apollo"

title = "usebeforefree"
description = "This is an example description"
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
build_search_index = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/tags", url = "/tags", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/usebeforefree/", icon = "github" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/
